#!/usr/bin/env python3
import argparse
import base64
import json
import os
import secrets

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def b64u(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def decode_key(value: str) -> bytes:
    value = value.strip()
    value += "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate one LEGACY AW1 offline activation code (migration/testing only)."
    )
    parser.add_argument("--serial", required=True, help="Sale/order serial shown in app")
    parser.add_argument(
        "--private-key-file",
        help="Text file containing the base64url Ed25519 private seed",
    )
    args = parser.parse_args()

    if args.private_key_file:
        key_text = open(args.private_key_file, "r", encoding="utf-8").read()
        key_text = [
            line.strip()
            for line in key_text.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ][-1]
    else:
        key_text = os.environ.get("ARTIST_WORKBENCH_LICENSE_PRIVATE_KEY", "").strip()

    if not key_text:
        raise SystemExit(
            "Missing private key. Pass --private-key-file or "
            "ARTIST_WORKBENCH_LICENSE_PRIVATE_KEY."
        )

    private_key = Ed25519PrivateKey.from_private_bytes(decode_key(key_text))
    payload = json.dumps(
        {
            "v": 1,
            "a": secrets.token_hex(10),
            "s": args.serial,
        },
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    signature = private_key.sign(payload)

    print(
        "WARNING: legacy AW1 code; new sales must be generated by the networked issuer.",
        file=__import__("sys").stderr,
    )
    print(f"AW1.{b64u(payload)}.{b64u(signature)}")


if __name__ == "__main__":
    main()
